language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -r requirements.txt"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
script: nosetests