language: python
python:
  - "2.7"
  - "3.4"
install: "pip install -e ."
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
script: nosetests
notifications:
  email: false
